title: <p align="center"> Vincent Vo </p>

logo: "/Images/main_logo.jpg?raw=true"

description:

  <div align="left" style="margin-bottom:10px;">
  <p style="margin-bottom:5px;">IT Systems Administrator</p>
  <p style="margin-top:5px;">IAM Advocate</p>
  <br>
  </div>

  <p style="margin-top:10px;">
  <a href="https://www.linkedin.com/in/vovincent12/" target="_blank" style="display:inline-flex; align-items:center; gap:5px;">
    <img src="https://cdn-icons-png.flaticon.com/512/174/174857.png" 
      alt=LinkedIn Icon" style="width:16px; height:16px;">
      LinkedIn</a>
  <br>
  <a href="https://github.com/venh-vo" target="_blank" style="display:inline-flex; align-items:center; gap:5px;">
    <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" 
      alt="Github Icon" style="width:16px; height:16px">
    GitHub</a>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-145578661-1 # Google Analytics tracking ID
# <a href="pdf/resume.pdf">Resume</a> |