title: <p align="center"> Vincent Vo </p>

logo: "/Images/main_logo.jpg?raw=true"

description:
  <p>
  <a href="https://www.linkedin.com/in/vovincent12/">LinkedIn</a> |
  <a href="https://github.com/venh-vo">GitHub</a>
  </p>
  
  <p>
  IT Systems Administrator
  <br><br>
  IAM Advocate
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-145578661-1 # Google Analytics tracking ID
# <a href="pdf/resume.pdf">Resume</a> |