logo: "/Images/main_logo.jpg?raw=true" # your photo (or logo) here
title: Vincent Vo
description: > # your text below (remove <br> elements if you don't need line breaks)
  IT Systems Administrator
  <br><br>
  IAM Advocate
  <br><br>
  <a href="https://www.linkedin.com/in/vovincent12/">LinkedIn</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here

