title: Vincent Vo

description: 
  IT Systems Administrator with expertise in Identity and Access Management (IAM), Zero Trust Architecture, and
  SaaS security. Proven success in automating user lifecycle management using API integrations, REST APIs, and
  low-code platforms like Workato, enabling scalable event-driven automation. Skilled in adaptive MFA, network
  segmentation, and SAML/OAuth SSO implementation to enforce secure access. Strong collaborator, supporting
  SOC2, ISO27001, and SOX compliance efforts. Passionate about emerging trends in passwordless
  authentication and cloud governance.

theme: jekyll-theme-minimal
url: "https://venh-vo.github.io"
markdown: kramdown